name: Build and Deploy vite front end

on:
    push:
        branches: [ main ]
    workflow_dispatch: 

permissions: 
    contents: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true


jobs:
    build:
        name: Compiling files
        runs-on: ubuntu-latest

        steps:
        # Step 1: Checkout the code
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup Node.JS
          uses: actions/setup-node@v3

        
        
        - name: Fetch and merge production branch
          run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                
                git fetch origin main

                # Checkout the production branch
                git checkout -b production
                
                # Reset the production branch to match the current main branch
                git reset --hard origin/main
                
                # Force push the current main state to production (overwriting it completely)
                git push origin production --force

        - name: Install dependencies and build
          working-directory: pages/FrontEnd
          run: |
            npm install
            npm run build

        - name: Remove source code
          run: |
            rm -rf pages/FrontEnd
        
        

        - name: Deploy
          if: success()
          run: |
            COMMIT_ID=${GITHUB_SHA}
            git add .
            git rm -r pages/FrontEnd
            git add pages/build/* -f
            git commit -m "Deploy Vite app to production branch (Triggered by commit ${COMMIT_ID})"
            git push origin HEAD:production
            
              
        
