name: Build and Deploy to Production

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies and Build Frontend
      run: |
        cd /pages/FrontEnd
        npm install
        npm run build

    - name: Push to Production Branch
      run: |
        git fetch origin
        git checkout main
        git branch -D production || true  # Delete local production branch if it exists
        git checkout -b production
        git push --force origin production
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
